name: C Compilation CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
      with:
        submodules: recursive

    - name: Compile bmp2oled
      run: gcc bmp2oled.c -o bmp2oled -lm

    - name: Compile oled2bmp
      run: gcc oled2bmp.c -o oled2bmp -lm
